# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('start_date', models.DateField()),
                ('physical_address', models.TextField()),
                ('mailing_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('locations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField(db_index=True, unique=True)),
                ('locations', models.TextField()),
                ('total_people', models.IntegerField()),
                ('total_households', models.IntegerField()),
                ('males', models.IntegerField()),
                ('females', models.IntegerField()),
                ('age_under_5', models.IntegerField()),
                ('age_5_9', models.IntegerField()),
                ('age_10_14', models.IntegerField()),
                ('age_15_19', models.IntegerField()),
                ('age_20_24', models.IntegerField()),
                ('age_25_34', models.IntegerField()),
                ('age_35_44', models.IntegerField()),
                ('age_45_54', models.IntegerField()),
                ('age_55_59', models.IntegerField()),
                ('age_60_64', models.IntegerField()),
                ('age_65_74', models.IntegerField()),
                ('age_75_84', models.IntegerField()),
                ('age_over_85', models.IntegerField()),
                ('edu_9th_grade', models.IntegerField()),
                ('edu_12th_grade', models.IntegerField()),
                ('edu_high_school', models.IntegerField()),
                ('edu_college', models.IntegerField()),
                ('edu_associate', models.IntegerField()),
                ('edu_bachelors', models.IntegerField()),
                ('edu_graduate', models.IntegerField()),
                ('incomes_below_10000', models.IntegerField()),
                ('incomes_10000_14999', models.IntegerField()),
                ('incomes_15000_24999', models.IntegerField()),
                ('incomes_25000_34999', models.IntegerField()),
                ('incomes_35000_49999', models.IntegerField()),
                ('incomes_50000_74999', models.IntegerField()),
                ('incomes_75000_99999', models.IntegerField()),
                ('incomes_100000_149999', models.IntegerField()),
                ('incomes_150000_199999', models.IntegerField()),
                ('incomes_over_200000', models.IntegerField()),
                ('industry_agriculture', models.IntegerField()),
                ('industry_construction', models.IntegerField()),
                ('industry_manufacturing', models.IntegerField()),
                ('industry_wholesale', models.IntegerField()),
                ('industry_retail', models.IntegerField()),
                ('industry_transportion', models.IntegerField()),
                ('industry_information', models.IntegerField()),
                ('industry_financial', models.IntegerField()),
                ('industry_professional', models.IntegerField()),
                ('industry_social', models.IntegerField()),
                ('industry_arts', models.IntegerField()),
                ('industry_other', models.IntegerField()),
                ('industry_public', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=255)),
                ('mp_nzone1', models.CharField(default='', max_length=255)),
                ('mp_nzone2', models.CharField(default='', max_length=255)),
                ('zone', models.CharField(db_index=True, max_length=255)),
                ('locations', models.TextField()),
            ],
        ),
    ]
