# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('physical_address', models.TextField()),
                ('mailing_address', models.TextField()),
            ],
        ),
    ]
