# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=255)),
                ('mp_nzone1', models.CharField(default='', max_length=255)),
                ('mp_nzone2', models.CharField(default='', max_length=255)),
                ('zone', models.CharField(db_index=True, max_length=255)),
                ('locations', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parking',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poi',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
