# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='incomes_25000_49999',
        ),
        migrations.AddField(
            model_name='population',
            name='incomes_25000_34999',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='incomes_35000_49999',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
